# Generated by Django 3.0.7 on 2020-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_auto_20201121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_pics/{user.id}'),
        ),
    ]
