# Generated by Django 3.0.7 on 2020-11-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0003_auto_20201121_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_pics/<django.db.models.query_utils.DeferredAttribute object at 0x04A7FC10>/'),
        ),
    ]
