# Generated by Django 3.0.7 on 2020-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0006_auto_20201121_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_pics/<django.db.models.query_utils.DeferredAttribute object at 0x03EAFC10>'),
        ),
    ]
