# Generated by Django 3.0.7 on 2020-11-21 20:52

from django.db import migrations, models
import siteuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0007_auto_20201121_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=siteuser.models.upload_to),
        ),
    ]
