# Generated by Django 3.0.7 on 2020-11-24 03:38

from django.db import migrations, models
import siteuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0008_auto_20201121_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=siteuser.models.upload_to),
        ),
    ]
